/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Snake;


import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cris
 */
public class Puntuajes extends javax.swing.JFrame {

    /**
     * Creates new form Puntuajes
     */
    public Puntuajes() {
        initComponents();
         setLocationRelativeTo(null);
         setSize(830,420);
    }

    /*Funtion that read ('Puntuaje.txt') the scores of all players that have been playing*/
    public void setData() {
        ArrayList<String[]> lineas = new ArrayList<>(); //ArrayList that contains all the score on the txt File
        try {
        File archivo = new File("Puntuajes.txt");
        String linea;
        Scanner lector = new Scanner(archivo);
        
            System.out.println(lineas.size());
        while ((linea = lector.nextLine())!= null) {
            lineas.add(linea.split(","));
        }
       
        } catch (Exception e) {
            System.out.println(e);
        }
        ArrayList<String[]> Mejores = new ArrayList<>(); //ArrayList that contaiins scores sort by points-time
        ArrayList<String[]> lineasCopia = new ArrayList<String[]>(lineas); //ArrayList that is a copy of the fist ArrayList of scores to avoid errors 
            while (true) {
            for (int i = 0; i < lineasCopia.size(); i++) {
                String[] lineaDato = lineasCopia.get(i);
                boolean mejor = mejoresTiempos(lineaDato, lineasCopia, i); //Call a function that compares a score with the other ones
                if (mejor) {
                    Mejores.add(lineaDato); //Adds the best score to the list
                    lineasCopia.remove(i); // deletes the best score from the copy
                }
            }
            if (lineasCopia.size() == 0) {
                break; //Breaks the while cicle just if the copy runs out of scores
            }
            }
            LlenarTablas(Mejores, lineas);
    }

    /*Fill the boths tables, one sort by date of game and the other one with the best*/
    public void LlenarTablas(ArrayList<String[]> tabla1, ArrayList<String[]> tabla2) {
               for (int i = 0; i < tabla1.size(); i++) { //A cicle to read the scores in the arrayList
                String[] data = tabla1.get(i);
                data[2] = convertTime(data[2]);
            DefaultTableModel modelo = (DefaultTableModel)jTable2.getModel(); //Gets the model of the table
            modelo.addRow(data);  //Add the score to a row
            }
            for (int i = 0; i < tabla2.size(); i++) { //The same as the other one but with the second table
                String[] data = tabla2.get(i);
            DefaultTableModel modelo2 = (DefaultTableModel)jTable1.getModel();
            modelo2.addRow(data); 
            }
    }

    /*Commpares a score with the other ones and retunr a boolean value*/
    public boolean mejoresTiempos(String[] dato1, ArrayList<String[]> Lista, int indice) {
        int cond = 0;
        int DatoP = Integer.parseInt(dato1[1]);
        int DatoT = Integer.parseInt(dato1[2]);
        for (int i = 0; i < Lista.size(); i++) {
            String[] puntuaje = Lista.get(i);
            int Puntos = Integer.parseInt(puntuaje[1]);
            int Tiempo = Integer.parseInt(puntuaje[2]);
            if (indice != i && Lista.size() != 1) {
                if (DatoP > Puntos) {
                } else if (DatoP == Puntos && DatoT <= Tiempo) {
                } else {
                    cond += 1;
                }
            }
        }
        
        if (cond != 0) {
            return false;
        } else {
            return true;
        }
    }
    
    /*Convert the time into readable time*/
    public String convertTime(String fecha) {
        int fechaInt = Integer.parseInt(fecha);
        int segundos = fechaInt / 1000;
        int contador = 0;
        String newTime = "";
        while (segundos > 60) {
            contador += 1;
            segundos = segundos - 60;
        }
        if (contador != 0) {
            newTime = String.valueOf(contador) + " minutos y " + String.valueOf(segundos) + " segundos";
        } else {
             newTime = String.valueOf(segundos) + " segundos";
        }
        
       return newTime; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBest = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTodo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mejores Tiempos");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuacion", "Tiempo", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("Nombre");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("Puntuacion");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Tiempo");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Fecha");
        }

        javax.swing.GroupLayout jBestLayout = new javax.swing.GroupLayout(jBest);
        jBest.setLayout(jBestLayout);
        jBestLayout.setHorizontalGroup(
            jBestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addContainerGap())
        );
        jBestLayout.setVerticalGroup(
            jBestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jBest);
        jBest.setBounds(496, 10, 320, 360);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuacion", "Tiempo", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        setData();
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Nombre");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Puntuacion");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Tiempo");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Fecha");
        }

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Todo");

        javax.swing.GroupLayout jTodoLayout = new javax.swing.GroupLayout(jTodo);
        jTodo.setLayout(jTodoLayout);
        jTodoLayout.setHorizontalGroup(
            jTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTodoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jTodoLayout.setVerticalGroup(
            jTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTodoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jTodo);
        jTodo.setBounds(6, 0, 490, 300);

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(50, 320, 105, 49);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Menu volver = new Menu();
        volver.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puntuajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puntuajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puntuajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puntuajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puntuajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBest;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel jTodo;
    // End of variables declaration//GEN-END:variables
}
