/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ahorcado;

import javax.swing.ImageIcon;
import General.*;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author Cris
 */
public class AGame extends javax.swing.JFrame {
    private String Nombre;
    private String nJ = "";
    String secretWord = getSecretWord();
    int nLSecretWord = secretWord.length();
    boolean gameEnded = false; 
    
    
    static String getSecretWord(){
        String [] words = {"GALLINA", "ESCUELA", "SEGUNDO", "DEPORTE", "DOMINIO"};
        Random r = new Random();
        int n = r.nextInt(words.length);
        System.out.println(words[n]);       
        return words[n];       
    }
    String imagenes[] = {
        ".\\src\\main\\java\\Recursos/na.png",
        ".\\src\\main\\java\\Recursos/head.png",
        ".\\src\\main\\java\\Recursos/headandbody.png",
        ".\\src\\main\\java\\Recursos/noarms.png",
        ".\\src\\main\\java\\Recursos/ded.png"
    
    
    };
    int indice = 0;
    
    /**
     * Creates new form AJuego
     */
    public AGame() {
        initComponents();
        ComGame();
//        nJ = JOptionPane.showInputDialog("Nombre del Jugador: ");
//        while (nJ.equals("")){
//            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre!");
//            nJ = JOptionPane.showInputDialog("Nombre del Jugador: ");
//        }
    
        Imgs();
    }
    public AGame(String name) {
        initComponents();
        
    }
    public void ComGame(){
        LetG = "";
        LetA = "";
        LetL = "";
        LetI = "";
        LetN = "";
        LblL1.setText("");
        LblL2.setText("");
        LblL3.setText("");
        LblL4.setText("");
        LblL5.setText("");
        LblL6.setText("");
        LblL7.setText("");
        ImageIcon Imagen = new ImageIcon(imagenes[0]);
        LabelVisor.setIcon(Imagen);
        indice = 0;
        trysP = 0;
        trysN = 0;
    }
    
    
    private void Imgs(){
//        LblH.setIcon(Ajustar.Resize(new ImageIcon(".\\src\\main\\java\\Recursos/Cabeza.png"),LblH));
//        LblT.setIcon(Ajustar.Resize(new ImageIcon(".\\src\\main\\java\\Recursos/Cuerpo.png"),LblT));
//        LblBD.setIcon(Ajustar.Resize(new ImageIcon(".\\src\\main\\java\\Recursos/manoI.png"),LblBD));
//        LblBI.setIcon(Ajustar.Resize(new ImageIcon(".\\src\\main\\java\\Recursos/manoD.png"),LblBI));
//        LblPD.setIcon(Ajustar.Resize(new ImageIcon(".\\src\\main\\java\\Recursos/pieI.png"),LblPD));
//        LblPI.setIcon(Ajustar.Resize(new ImageIcon(".\\src\\main\\java\\Recursos/pied.png"),LblPI));
        
        
//        ImageIcon icono = new ImageIcon(".\\src\\main\\java\\Recursos/icono.png");
//        this.setIconImage(icono.getImage());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTeclado = new javax.swing.JPanel();
        BtnA = new javax.swing.JButton();
        BtnB = new javax.swing.JButton();
        BtnD = new javax.swing.JButton();
        BtnC = new javax.swing.JButton();
        BtnE = new javax.swing.JButton();
        BtnF = new javax.swing.JButton();
        BtnG = new javax.swing.JButton();
        BtnH = new javax.swing.JButton();
        BtnI = new javax.swing.JButton();
        BtnJ = new javax.swing.JButton();
        BtnK = new javax.swing.JButton();
        BtnL = new javax.swing.JButton();
        BtnM = new javax.swing.JButton();
        BtnN = new javax.swing.JButton();
        BtnO = new javax.swing.JButton();
        BtnP = new javax.swing.JButton();
        BtnQ = new javax.swing.JButton();
        BtnR = new javax.swing.JButton();
        BtnS = new javax.swing.JButton();
        BtnT = new javax.swing.JButton();
        BtnU = new javax.swing.JButton();
        BtnV = new javax.swing.JButton();
        BtnW = new javax.swing.JButton();
        BtnX = new javax.swing.JButton();
        BtnY = new javax.swing.JButton();
        BtnZ = new javax.swing.JButton();
        BtnNn = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        LblE2 = new javax.swing.JLabel();
        LblL1 = new javax.swing.JLabel();
        LblL2 = new javax.swing.JLabel();
        LblL3 = new javax.swing.JLabel();
        LblL4 = new javax.swing.JLabel();
        LblL5 = new javax.swing.JLabel();
        LblL6 = new javax.swing.JLabel();
        LblL7 = new javax.swing.JLabel();
        LblE3 = new javax.swing.JLabel();
        LblE4 = new javax.swing.JLabel();
        LblE5 = new javax.swing.JLabel();
        LblE6 = new javax.swing.JLabel();
        LblE7 = new javax.swing.JLabel();
        LblE8 = new javax.swing.JLabel();
        LabelVisor = new javax.swing.JLabel();
        BtnNewGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(555, 458));
        setResizable(false);
        getContentPane().setLayout(null);

        PanelTeclado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanelTeclado.setLayout(null);

        BtnA.setText("A");
        BtnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnA);
        BtnA.setBounds(6, 5, 50, 40);

        BtnB.setText("B");
        BtnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnB);
        BtnB.setBounds(73, 5, 50, 40);

        BtnD.setText("D");
        BtnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnD);
        BtnD.setBounds(207, 5, 50, 40);

        BtnC.setText("C");
        BtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnC);
        BtnC.setBounds(140, 5, 50, 40);

        BtnE.setText("E");
        BtnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnE);
        BtnE.setBounds(6, 54, 50, 40);

        BtnF.setText("F");
        BtnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnF);
        BtnF.setBounds(73, 54, 50, 40);

        BtnG.setText("G");
        BtnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnG);
        BtnG.setBounds(140, 54, 50, 40);

        BtnH.setText("H");
        BtnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnH);
        BtnH.setBounds(207, 54, 50, 40);

        BtnI.setText("I");
        BtnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnI);
        BtnI.setBounds(6, 103, 50, 40);

        BtnJ.setText("J");
        BtnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnJ);
        BtnJ.setBounds(73, 103, 50, 40);

        BtnK.setText("K");
        BtnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnK);
        BtnK.setBounds(140, 103, 50, 40);

        BtnL.setText("L");
        BtnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnL);
        BtnL.setBounds(207, 103, 50, 40);

        BtnM.setText("M");
        BtnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnM);
        BtnM.setBounds(6, 152, 50, 40);

        BtnN.setText("N");
        BtnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnN);
        BtnN.setBounds(73, 152, 50, 40);

        BtnO.setText("O");
        BtnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnO);
        BtnO.setBounds(207, 152, 50, 40);

        BtnP.setText("P");
        BtnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnP);
        BtnP.setBounds(6, 201, 50, 40);

        BtnQ.setText("Q");
        BtnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnQ);
        BtnQ.setBounds(73, 201, 50, 40);

        BtnR.setText("R");
        BtnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnR);
        BtnR.setBounds(140, 200, 50, 40);

        BtnS.setText("S");
        BtnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnS);
        BtnS.setBounds(207, 201, 50, 40);

        BtnT.setText("T");
        BtnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnT);
        BtnT.setBounds(6, 250, 50, 40);

        BtnU.setText("U");
        BtnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnU);
        BtnU.setBounds(73, 250, 50, 40);

        BtnV.setText("V");
        BtnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnV);
        BtnV.setBounds(140, 250, 50, 40);

        BtnW.setText("W");
        BtnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnWActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnW);
        BtnW.setBounds(207, 250, 50, 40);

        BtnX.setText("X");
        BtnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnX);
        BtnX.setBounds(40, 300, 50, 40);

        BtnY.setText("Y");
        BtnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnYActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnY);
        BtnY.setBounds(110, 300, 50, 40);

        BtnZ.setText("Z");
        BtnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnZActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnZ);
        BtnZ.setBounds(180, 300, 50, 40);

        BtnNn.setText("Ñ");
        BtnNn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNnActionPerformed(evt);
            }
        });
        PanelTeclado.add(BtnNn);
        BtnNn.setBounds(140, 152, 50, 40);

        getContentPane().add(PanelTeclado);
        PanelTeclado.setBounds(250, 10, 270, 350);

        BtnExit.setText("Volver");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit);
        BtnExit.setBounds(430, 370, 90, 40);

        LblE2.setText("_");
        getContentPane().add(LblE2);
        LblE2.setBounds(160, 370, 20, 20);

        LblL1.setText("G");
        LblL1.setName("LblL1"); // NOI18N
        getContentPane().add(LblL1);
        LblL1.setBounds(40, 370, 10, 16);

        LblL2.setText("A");
        getContentPane().add(LblL2);
        LblL2.setBounds(60, 370, 10, 16);

        LblL3.setText("L");
        getContentPane().add(LblL3);
        LblL3.setBounds(80, 370, 10, 16);

        LblL4.setText("L");
        getContentPane().add(LblL4);
        LblL4.setBounds(100, 370, 10, 16);

        LblL5.setText("I");
        getContentPane().add(LblL5);
        LblL5.setBounds(120, 370, 10, 16);

        LblL6.setText("N");
        getContentPane().add(LblL6);
        LblL6.setBounds(140, 370, 10, 16);

        LblL7.setText("A");
        getContentPane().add(LblL7);
        LblL7.setBounds(160, 370, 10, 16);

        LblE3.setText("_");
        getContentPane().add(LblE3);
        LblE3.setBounds(40, 370, 20, 20);

        LblE4.setText("_");
        getContentPane().add(LblE4);
        LblE4.setBounds(60, 370, 20, 20);

        LblE5.setText("_");
        getContentPane().add(LblE5);
        LblE5.setBounds(80, 370, 20, 20);

        LblE6.setText("_");
        getContentPane().add(LblE6);
        LblE6.setBounds(100, 370, 20, 20);

        LblE7.setText("_");
        getContentPane().add(LblE7);
        LblE7.setBounds(120, 370, 20, 20);

        LblE8.setText("_");
        getContentPane().add(LblE8);
        LblE8.setBounds(140, 370, 20, 20);

        LabelVisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(LabelVisor);
        LabelVisor.setBounds(50, 70, 150, 210);

        BtnNewGame.setText("Nuevo Juego");
        BtnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewGameActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNewGame);
        BtnNewGame.setBounds(320, 370, 100, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnHActionPerformed

    private void BtnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMActionPerformed
        if (indice == 5 ) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnMActionPerformed

    private void BtnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAActionPerformed
        if (secretWord.contains("A")){
        if (indice < 5){
             LetA += "A";
             LblL2.setText(LetA);
             LblL7.setText(LetA);
             trysP = trysP + 1;
         
        if (trysP == 5){
             JOptionPane.showMessageDialog(null, "Has Salvado a Kermit, hurra!!!");
        }
        else{
             JOptionPane.showMessageDialog(null, "Excelente, falta menos para rescatar a nuestro amigo saltarín");
             BtnA.setEnabled(false);
        }
        
        }else{}
        }else{
          if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnAActionPerformed
    }
    private void BtnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBActionPerformed
          if (indice ==5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                }         
    }//GEN-LAST:event_BtnBActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Realmente desea regresar al menú?", "Está seguro?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       if (respuesta == 0){
           dispose();
           AMenu AhoMenu = new AMenu();
           AhoMenu.setVisible(true);
           }
           
           
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewGameActionPerformed
        ComGame();
    }//GEN-LAST:event_BtnNewGameActionPerformed

    private void BtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnCActionPerformed

    private void BtnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnDActionPerformed

    private void BtnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnEActionPerformed

    private void BtnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnFActionPerformed

    private void BtnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnGActionPerformed

    private void BtnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnIActionPerformed

    private void BtnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnJActionPerformed

    private void BtnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnKActionPerformed

    private void BtnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnLActionPerformed

    private void BtnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnNActionPerformed

    private void BtnNnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNnActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnNnActionPerformed

    private void BtnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnOActionPerformed

    private void BtnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnPActionPerformed

    private void BtnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnQActionPerformed

    private void BtnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnRActionPerformed

    private void BtnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnSActionPerformed

    private void BtnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnTActionPerformed

    private void BtnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnUActionPerformed

    private void BtnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnVActionPerformed

    private void BtnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnWActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnWActionPerformed

    private void BtnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnXActionPerformed

    private void BtnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnYActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnYActionPerformed

    private void BtnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnZActionPerformed
        if (indice == 5) {
                indice = 5;
        }
        else{
                indice++;
                ImageIcon Imagen = new ImageIcon(imagenes[indice]);
                LabelVisor.setIcon(Imagen);
                } 
    }//GEN-LAST:event_BtnZActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AGame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnA;
    private javax.swing.JButton BtnB;
    private javax.swing.JButton BtnC;
    private javax.swing.JButton BtnD;
    private javax.swing.JButton BtnE;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnF;
    private javax.swing.JButton BtnG;
    private javax.swing.JButton BtnH;
    private javax.swing.JButton BtnI;
    private javax.swing.JButton BtnJ;
    private javax.swing.JButton BtnK;
    private javax.swing.JButton BtnL;
    private javax.swing.JButton BtnM;
    private javax.swing.JButton BtnN;
    private javax.swing.JButton BtnNewGame;
    private javax.swing.JButton BtnNn;
    private javax.swing.JButton BtnO;
    private javax.swing.JButton BtnP;
    private javax.swing.JButton BtnQ;
    private javax.swing.JButton BtnR;
    private javax.swing.JButton BtnS;
    private javax.swing.JButton BtnT;
    private javax.swing.JButton BtnU;
    private javax.swing.JButton BtnV;
    private javax.swing.JButton BtnW;
    private javax.swing.JButton BtnX;
    private javax.swing.JButton BtnY;
    private javax.swing.JButton BtnZ;
    private javax.swing.JLabel LabelVisor;
    private javax.swing.JLabel LblE2;
    private javax.swing.JLabel LblE3;
    private javax.swing.JLabel LblE4;
    private javax.swing.JLabel LblE5;
    private javax.swing.JLabel LblE6;
    private javax.swing.JLabel LblE7;
    private javax.swing.JLabel LblE8;
    private javax.swing.JLabel LblL1;
    private javax.swing.JLabel LblL2;
    private javax.swing.JLabel LblL3;
    private javax.swing.JLabel LblL4;
    private javax.swing.JLabel LblL5;
    private javax.swing.JLabel LblL6;
    private javax.swing.JLabel LblL7;
    private javax.swing.JPanel PanelTeclado;
    // End of variables declaration//GEN-END:variables
     int trysP = 0;
     int trysN = 0;
     String LetG = "";
     String LetA = "";
     String LetL = "";
     String LetI = "";
     String LetN = "";
}
