/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ahorcado;

/**
 *
 * @author Cris
 */
public class AJuego extends javax.swing.JFrame {
    private String Nombre;
    /**
     * Creates new form AJuego
     */
    public AJuego() {
        initComponents();
    }
    public AJuego(String name) {
        initComponents();
        this.Nombre = Nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setText("A");
        jPanel1.add(jButton1);
        jButton1.setBounds(6, 5, 50, 40);

        jButton2.setText("B");
        jPanel1.add(jButton2);
        jButton2.setBounds(73, 5, 50, 40);

        jButton3.setText("D");
        jPanel1.add(jButton3);
        jButton3.setBounds(207, 5, 50, 40);

        jButton4.setText("C");
        jPanel1.add(jButton4);
        jButton4.setBounds(140, 5, 50, 40);

        jButton5.setText("E");
        jPanel1.add(jButton5);
        jButton5.setBounds(6, 54, 50, 40);

        jButton6.setText("F");
        jPanel1.add(jButton6);
        jButton6.setBounds(73, 54, 50, 40);

        jButton7.setText("G");
        jPanel1.add(jButton7);
        jButton7.setBounds(140, 54, 50, 40);

        jButton8.setText("H");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(207, 54, 50, 40);

        jButton9.setText("I");
        jPanel1.add(jButton9);
        jButton9.setBounds(6, 103, 50, 40);

        jButton10.setText("J");
        jPanel1.add(jButton10);
        jButton10.setBounds(73, 103, 50, 40);

        jButton11.setText("K");
        jPanel1.add(jButton11);
        jButton11.setBounds(140, 103, 50, 40);

        jButton12.setText("L");
        jPanel1.add(jButton12);
        jButton12.setBounds(207, 103, 50, 40);

        jButton13.setText("M");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(6, 152, 50, 40);

        jButton14.setText("N");
        jPanel1.add(jButton14);
        jButton14.setBounds(73, 152, 50, 40);

        jButton15.setText("O");
        jPanel1.add(jButton15);
        jButton15.setBounds(207, 152, 50, 40);

        jButton16.setText("P");
        jPanel1.add(jButton16);
        jButton16.setBounds(6, 201, 50, 40);

        jButton17.setText("Q");
        jPanel1.add(jButton17);
        jButton17.setBounds(73, 201, 50, 40);

        jButton18.setText("R");
        jPanel1.add(jButton18);
        jButton18.setBounds(140, 201, 50, 40);

        jButton19.setText("S");
        jPanel1.add(jButton19);
        jButton19.setBounds(207, 201, 50, 40);

        jButton20.setText("T");
        jPanel1.add(jButton20);
        jButton20.setBounds(6, 250, 50, 40);

        jButton21.setText("U");
        jPanel1.add(jButton21);
        jButton21.setBounds(73, 250, 50, 40);

        jButton22.setText("V");
        jPanel1.add(jButton22);
        jButton22.setBounds(140, 250, 50, 40);

        jButton23.setText("W");
        jPanel1.add(jButton23);
        jButton23.setBounds(207, 250, 50, 40);

        jButton24.setText("X");
        jPanel1.add(jButton24);
        jButton24.setBounds(59, 299, 50, 40);

        jButton25.setText("Y");
        jPanel1.add(jButton25);
        jButton25.setBounds(114, 299, 50, 40);

        jButton26.setText("Z");
        jPanel1.add(jButton26);
        jButton26.setBounds(169, 299, 50, 40);

        jButton27.setText("Ñ");
        jPanel1.add(jButton27);
        jButton27.setBounds(140, 152, 50, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(310, 80, 280, 350);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cabeza.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 140, 60, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/manoD.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 170, 50, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/manoI.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 160, 30, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cuerpo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 160, 80, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/pied.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 210, 40, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/pieI.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 200, 50, 90);

        jButton28.setText("Volver");
        getContentPane().add(jButton28);
        jButton28.setBounds(48, 468, 136, 74);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
