/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ahorcado;

import java.awt.Color;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author guerreroandrey5
 */

public class APuntajes extends javax.swing.JFrame {

    /**
     * Creates new form APuntajes
     */
    private String ruta = System.getProperties().getProperty("user.dir");
    public APuntajes() {
        initComponents();
        THistoryLoad();
    }
    /*Loads the data from a TXT in the project, the files has the Scores*/
    void THistoryLoad(){
        DefaultTableCellRenderer MyHeaderRender = new DefaultTableCellRenderer();
        MyHeaderRender.setBackground(Color.decode("#5A5A5A"));             
        File archivo = null;
        FileReader FileR = null;
        BufferedReader BufferedR = null;
        try{
            archivo = new File(ruta + "//HistorialHanged.txt");
            FileR = new FileReader(archivo);
            BufferedR = new BufferedReader(FileR);
            String data;
            DefaultTableModel HistoryTablez = new DefaultTableModel();
            HistoryTablez.addColumn("Historial de Ahorcado");
            while((data = BufferedR.readLine()) != null){
                System.out.println(data);
                HistoryTablez.addRow(new String []{data});
            }   
            HistoryTable.setModel(HistoryTablez);
            HistoryTable.getTableHeader().getColumnModel().getColumn(0).setHeaderRenderer(MyHeaderRender);
        }catch (Exception e){JOptionPane.showMessageDialog(null, "No hay datos registrados sobre Records, el registro se mostrará en blanco");}finally{try{if(null!=FileR) {FileR.close();}}catch(IOException e2){
            
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlnScores = new javax.swing.JPanel();
        LblHistory = new javax.swing.JLabel();
        BtnMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial de Ahorcado");
        setName("FScores"); // NOI18N
        setResizable(false);

        PlnScores.setBackground(new java.awt.Color(63, 63, 63));

        LblHistory.setForeground(new java.awt.Color(204, 204, 204));
        LblHistory.setText("Historial de Partidas");

        BtnMenu.setBackground(new java.awt.Color(63, 63, 63));
        BtnMenu.setForeground(new java.awt.Color(204, 204, 204));
        BtnMenu.setText("Volver al Menu");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        HistoryTable.setBackground(new java.awt.Color(63, 63, 63));
        HistoryTable.setForeground(new java.awt.Color(204, 204, 204));
        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        HistoryTable.setEnabled(false);
        HistoryTable.setGridColor(new java.awt.Color(63, 63, 63));
        HistoryTable.setSelectionBackground(new java.awt.Color(63, 63, 63));
        HistoryTable.setSelectionForeground(new java.awt.Color(63, 63, 63));
        HistoryTable.setShowGrid(true);
        HistoryTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(HistoryTable);

        javax.swing.GroupLayout PlnScoresLayout = new javax.swing.GroupLayout(PlnScores);
        PlnScores.setLayout(PlnScoresLayout);
        PlnScoresLayout.setHorizontalGroup(
            PlnScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlnScoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PlnScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addGroup(PlnScoresLayout.createSequentialGroup()
                        .addComponent(LblHistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnMenu)))
                .addContainerGap())
        );
        PlnScoresLayout.setVerticalGroup(
            PlnScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlnScoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PlnScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnMenu)
                    .addComponent(LblHistory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlnScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlnScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Realmente desea regresar al menú?", "Está seguro?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       if (respuesta == 0){
           dispose();
           AMenu AhoMenu = new AMenu();
           AhoMenu.setVisible(true);
       }
    }//GEN-LAST:event_BtnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APuntajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenu;
    private javax.swing.JTable HistoryTable;
    private javax.swing.JLabel LblHistory;
    private javax.swing.JPanel PlnScores;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
